name: voltz
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^13.0.2
  google_maps_flutter: ^2.5.3
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  fl_chart: ^0.66.0
  timeago: ^3.7.0
  table_calendar: ^3.1.3
  flutter_local_notifications: ^18.0.1
  photo_view: ^0.14.0
  path: ^1.8.3
  logger: ^2.0.2+1
  supabase_flutter: ^2.3.4
  supabase: ^2.0.8
  uuid: ^4.3.3
  image_picker: ^1.1.2
  intl: ^0.19.0
  flutter_animate: ^4.5.2
  material: ^1.0.0+2
  lottie: ^2.7.0
  flashy_tab_bar2: ^0.0.10
  permission_handler: ^11.0.1
  google_places_flutter: ^2.0.9
  geocoding: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

# Flutter Launcher Icons configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/logo.png"
  min_sdk_android: 21
  adaptive_icon_padding: true
  remove_alpha_ios: true
  background_color_ios: "#FFFFFF"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo.png
    - assets/animations/
    - assets/images/
